---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host belongs to {{ env }} environment!!!"

- name: Change mongodb config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod

