---
- name: all hosts configuration
  hosts: all
  become: yes
  gather_facts: False

  tasks:
    - name: install python
      raw: test -e /usr/bin/python || (apt update -y && apt install python -y)
      changed_when: False
