---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  - name: Install ruby and rubygems and required packages
    become: true
    apt: 
      name:
        - ruby-full
        - ruby-bundler
        - build-essential
      state: present
