---
- name: Configure application
  hosts: tag_reddit-app
  become: true
  vars:
    db_host: reddit-db
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config

    - name: enable Puma
      service: name=puma enabled=yes state=started

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma.service state=restarted

