---
- name: Configure mongod
  hosts: tag_reddit-db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongodb config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted

- name: deploy reddit-app
  hosts: tag_reddit-app
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch latest app version
      git:
        repo: https://github.com/express42/reddit.git
        dest: /opt/reddit
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: /opt/reddit

- name: Configure application
  hosts: tag_reddit-app
  tags: app-tag
  become: true
  vars:
    db_host: reddit-db
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config

    - name: enable Puma
      service: name=puma enabled=yes state=started

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma.service state=restarted



